server:
  port: 8081
spring:
  app:
    jwtCookie: refreshToken
  application:
    name: hrm-backend
  datasource:
    url: jdbc:mysql://localhost:3308/hrm_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true


security:
  oauth2:
    client:
      registration:
        strava:
          client-id: 184102
          client-secret: bc20bba1d5b6ea033783e8aedaf59de38f8e156d
          scope: read,activity:read_all
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8081/oauth2/callback
      provider:
        strava:
          authorization-uri: https://www.strava.com/oauth/authorize
          token-uri: https://www.strava.com/oauth/token
          user-info-uri: https://www.strava.com/api/v3/athlete
          user-name-attribute: id

frontend:
  url: http://localhost:3000

jwt:
  secret: 8b66d6e9b70c72dd14b47506679a8c0a7c35ebade31376edeff07d7c83de8c72
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds:  604800

logging:
  level:
    org:
      springframework:
        security=TRACE: